# fly.toml app configuration file generated for gliondar-api on 2023-05-05T15:38:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gliondar-api"
primary_region = "ams"

[build]
  image = "registry.fly.io/gliondar-api:latest"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
