app = "gliondar-api"
primary_region = "ams"

[build]
  image = "registry.fly.io/gliondar-api:latest"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
