name: Build

on:
  push:
    branches:
      - chore/serve-mock-api-data

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build -t registry.fly.io/gliondar-api:latest -f ./apps/api/Dockerfile .

      - name: Authenticate with registry
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Push image
        run: docker push registry.fly.io/gliondar-api

#      - name: Authenticate with registry
#        run: doctl registry login --expiry-seconds 600
#
#      - name: Push to registry
#        run: docker push registry.digitalocean.com/syzible/gliondar-api:latest
#
      - name: Deploy to Fly
        run: flyctl deploy --image registry.fly.io/gliondar-api:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
