name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if app is affected
        run: npx nx-ignore api --affected --base=origin/main --head=HEAD --silent

      - name: Authenticate with registry
        uses: docker/login-action@v3
        with:
          username: edmondoflynn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and deploy api
        run: |
          docker build -t edmondoflynn/gliondar-api:latest -f ./apps/api/Dockerfile .
          docker push edmondoflynn/gliondar-api:latest

      - name: Promote image
        uses: floms/action-caprover@v1
        with:
          host: https://captain.root.syzible.com
          app: gliondar-api
          password: ${{ secrets.CAPROVER_PASSWORD }}
          image: edmondoflynn/gliondar-api:latest
